name: MIT license compatibility checker

on:
  push:
    paths:
      - 'pyproject.toml'
      - '.github/workflows/license-checker.yaml'
  pull_request:
    paths:
      - 'pyproject.toml'
      - '.github/workflows/license-checker.yaml'
  workflow_dispatch:

concurrency: liccheck-${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      # Set an environment variable to select pip's cache directory for us to actually cache between runs.
      PIP_CACHE_DIR: /tmp/pip-cache-dir
      # The Python version your project uses. Feel free to change this if required.
      PYTHON_VERSION: 3.9
    steps:
      # Checks out the repository in the current folder.
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.5


      - name: Install dependencies
        run: |
          pip install liccheck wheel
          poetry install
      - name: Check for compatibility with MIT license
        run: |
          poetry export --format requirements.txt --output requirements.txt
          pip install -r requirements.txt
          cat requirements.txt
          liccheck -r requirements.txt
