# GitHub Action Workflow enforcing our code style.

name: Lint, Build & Deploy

# Trigger the workflow on both push (to the main repository)
# and pull requests (against the main repository, but from any repo).
on: [push, pull_request]

# Brand new concurrency setting! This ensures that not more than one run can be triggered for the same commit.
# It is useful for pull requests coming from the main repository since both triggers will match.
concurrency: lint-${{ github.sha }}

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python_version: [3.7, 3.8, 3.9]
    runs-on: ubuntu-latest

    env:
      # Set an environment variable to select pip's cache directory for us to actually cache between runs.
      PIP_CACHE_DIR: /tmp/pip-cache-dir

    steps:
      # Checks out the repository in the current folder.
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install wheel pre-commit

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.3

      - name: Install poetry dependencies
        run: |
          poetry install

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
