# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on:
  push:
    paths:
      - '*.py'
      - '.github/workflows/pytest.yml'
  pull_request:
    paths:
      - '*.py'
      - '.github/workflows/pytest.yml'

concurrency: test-${{ github.sha }}

jobs:

  test:

    runs-on: ubuntu-latest

    env:
      # Set an environment variable to select pip's cache directory for us to actually cache between runs.
      PIP_CACHE_DIR: /tmp/pip-cache-dir
      # The Python version your project uses. Feel free to change this if required.
      PYTHON_VERSION: 3.9
    steps:
      # Checks out the repository in the current folder.
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.5

      - name: Install dependencies
        run: |
          pip install pytest wheel
          poetry install
          poetry export --format requirements.txt --output requirements.txt
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          python -m pytest
